# Generated by Django 4.2 on 2025-01-04 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('categoria', models.CharField(choices=[('Programación', 'Programación'), ('Data', 'Data'), ('Redes', 'Redes'), ('QA', 'QA'), ('UX/UI', 'UX/UI')], max_length=50)),
                ('seniority', models.CharField(choices=[('Junior', 'Junior'), ('Semi Senior', 'Semi Senior'), ('Senior', 'Senior'), ('Manager', 'Manager')], max_length=50)),
                ('tareas', models.TextField()),
                ('requisitos_excluyentes', models.TextField()),
                ('requisitos_deseables', models.TextField()),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Finalizada', 'Finalizada')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Programación', 'Programación'), ('Data', 'Data'), ('Redes', 'Redes'), ('QA', 'QA'), ('UX/UI', 'UX/UI')], max_length=50)),
                ('seniority', models.CharField(choices=[('Junior', 'Junior'), ('Semi Senior', 'Semi Senior'), ('Senior', 'Senior'), ('Manager', 'Manager')], max_length=50)),
                ('archivo_cv', models.FileField(upload_to='cvs/')),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Prueba técnica', 'Prueba técnica'), ('Entrevistas', 'Entrevistas'), ('Preocupacional', 'Preocupacional'), ('Contratado', 'Contratado'), ('Rechazado', 'Rechazado')], max_length=50)),
                ('id_busqueda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='App.busqueda')),
                ('id_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='App.candidato')),
            ],
        ),
    ]
